# Auto-generated by the release workflow from the git tag.
# In development this file is a placeholder; the CI overwrites it before
# building the PyInstaller bundle so the frozen app shows the correct version.
__version__ = "dev"
