#!/usr/bin/env python3
"""
Bethesda Strings AI Translator
Translate .strings/.dlstrings/.ilstrings files using local Ollama AI
"""
import os
import sys
import logging
from pathlib import Path

os.environ.setdefault("NO_AT_BRIDGE", "1")

try:
    from _version import __version__  # type: ignore[import]  # generated by release CI
except ImportError:
    __version__ = "dev"
from PySide6.QtWidgets import QApplication
from PySide6.QtCore import QLocale, Qt, QTranslator
from PySide6.QtGui import QFont
from gui.main_window import MainWindow
from gui.theme_manager import ThemeManager
from gui.app_settings import load_settings, apply_theme, get_config_path

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    handlers=[
        logging.StreamHandler(sys.stdout),
        logging.FileHandler('translator.log', encoding='utf-8')
    ]
)
logger = logging.getLogger(__name__)

# Global theme manager instance
theme_manager = ThemeManager()

# RTL languages — Qt mirrors the entire layout automatically
_RTL_LANGS = {"ar", "he", "fa", "ur"}


def _load_translator(app: QApplication, translator: QTranslator, locale_code: str) -> None:
    """Install a .qm translation file for *locale_code* (BCP-47, e.g. 'uk_UA').

    Falls back silently to English when the .qm file is missing or fails to load.
    Also configures QLocale and RTL layout direction.
    """
    lang = locale_code.split("_")[0] if locale_code else "en"

    # RTL layout for Arabic / Hebrew / Farsi / Urdu
    if lang in _RTL_LANGS:
        app.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
    else:
        app.setLayoutDirection(Qt.LayoutDirection.LeftToRight)

    if not locale_code or locale_code == "en":
        QLocale.setDefault(QLocale(QLocale.Language.English, QLocale.Country.UnitedStates))
        return

    qm_path = Path(__file__).parent / "gui" / "translations" / f"{locale_code}.qm"
    if not qm_path.exists():
        logger.warning("Translation file not found: %s", qm_path)
        return

    if translator.load(str(qm_path)):
        app.installTranslator(translator)
        qt_locale = QLocale(locale_code.replace("_", "-"))
        QLocale.setDefault(qt_locale)
        logger.info("Loaded UI translation: %s", locale_code)
    else:
        logger.error("Failed to load translation file: %s", qm_path)


def main():
    """Main entry point for the application."""
    # Enable high-DPI scaling
    QApplication.setHighDpiScaleFactorRoundingPolicy(
        Qt.HighDpiScaleFactorRoundingPolicy.PassThrough
    )

    # Force Qt's own file dialogs instead of native ones.
    # Native dialogs (GTK/KDE portal) can deadlock the Qt event loop on Linux,
    # making the app completely unresponsive and blocking the compositor's focus
    # grab — reproducible on tiling WMs (i3, sway, Hyprland) and mixed DE setups.
    # This must be set before QApplication is created.
    QApplication.setAttribute(Qt.ApplicationAttribute.AA_DontUseNativeDialogs)

    app = QApplication(sys.argv)
    app.setApplicationName("Bethesda Strings AI Translator")
    app.setApplicationVersion("0.2.1")
    app.setOrganizationName("BethesdaModTools")

    # Load settings (JSON config > QSettings > defaults) with env overrides
    settings = load_settings()
    logger.info(f"Config loaded from {get_config_path()}")

    # Apply saved theme
    apply_theme(app, settings.theme)

    # Setup translator — generic locale-code based loader
    translator = QTranslator()
    locale_code = settings.ui_language  # BCP-47, e.g. "uk_UA", "de_DE", "en"
    _load_translator(app, translator, locale_code)

    # Apply user font size (0 = OS default; 8-24 = explicit pt size)
    if settings.font_size > 0:
        base_font = QFont()
        base_font.setPointSize(settings.font_size)
        app.setFont(base_font)

    window = MainWindow(settings=settings, theme_manager=theme_manager)

    # Set application icon
    icon_path = Path(__file__).parent / "resources" / "app_icon.png"
    if icon_path.exists():
        from PySide6.QtGui import QIcon
        icon = QIcon(str(icon_path))
        app.setWindowIcon(icon)
        window.setWindowIcon(icon)

    window.show()

    # Open file passed as a command-line argument (file-association / double-click).
    # Use singleShot(0) so the event loop is running before the file-open path
    # tries to show error dialogs or interact with the welcome widget.
    if len(sys.argv) > 1:
        file_arg = Path(sys.argv[1])
        if file_arg.is_file():
            from PySide6.QtCore import QTimer
            QTimer.singleShot(0, lambda: window._open_file_path(str(file_arg)))

    # Process events once to ensure thread starts properly
    app.processEvents()

    sys.exit(app.exec())


if __name__ == "__main__":
    main()
